# Generated by Django 6.0.3 on 2026-04-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('shop_owner', 'Medicine Shop Owner')], default='shop_owner', max_length=20),
        ),
    ]
