# Generated by Django 6.0.3 on 2026-04-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='low_stock_threshold',
            field=models.IntegerField(default=10),
        ),
    ]
